import "./styles.css";
import Sidebar from "@/components/layout/sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen">
          <div className="flex">
            <Sidebar />
            <div className="flex flex-col flex-grow w-screen md:w-full min-h-screen">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
